eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/
---
spring:
  application:
    name: cloud-discovery-service
  profiles: one
server:
  port: 8001
eureka:
  instance:
    hostname: peer1
---
spring:
  application:
    name: cloud-discovery-service
  profiles: two
server:
  port: 8002
eureka:
  instance:
    hostname: peer2
---
spring:
  application:
    name: cloud-discovery-service
  profiles: three
server:
  port: 8003
eureka:
  instance:
    hostname: peer3