server:
  port: 5757

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mar?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    maxActive: 20
    maxIdle: 20
    minIdle: 5
    maxWait: 60000
  redis:
    database: 1
    host: localhost
    port: 6379
    cluster:
      max-redirects: 8
    pool:
      max-wait: -1
      max-active: 8
      max-idle: 8
      min-idle: 0
    timeout: 0
  jackson:
    default-property-inclusion: non_null

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mar.entity

  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #分页
    #刷新mapper 调试神器
    refresh-mapper: true
    #实体传入增加通用操作字段
    meta-object-handler: com.mar.handler.AutoCommonFieldsHandler
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging
logging:
  config: classpath:log4j2.yml



